import type { IconFn } from './icons.ts';
import {
    iconHome,
    iconMail,
    iconLightbulb,
    iconFolderKanban,
    iconBarChart,
    iconGitBranch,
    iconPeople,
    iconBuilding,
    iconPerson,
    iconShield,
    iconCreditCard,
    iconDatabase,
    iconPalette,
} from './icons.ts';

export interface PageEntry {
    title: string;
    layout: 'sidebar' | 'standalone';
    inSidebarNav?: boolean;
    sidebarKey?: string;
    sourceDir: string;
    sourceFile: string;
    icon?: IconFn;
    keywords?: string;
    searchable?: boolean;
    requiresSchema?: boolean;
    cssBundles?: string[];
    loader: () => Promise<{
        init: (
            params?: Record<string, string>,
        ) => void | Promise<void>;
    }>;
}

export const PAGE_REGISTRY: Record<
    string,
    PageEntry
> = {
    dashboard: {
        title: 'Dashboard',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'dashboard',
        sourceFile: 'index',
        icon: iconHome,
        keywords: 'home overview',
        loader: () => import('../dashboard/index'),
    },
    organization: {
        title: 'Organization',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'organization',
        sourceFile: 'index',
        icon: iconBuilding,
        keywords:
            'organization billing plan',
        cssBundles: ['pages-organization'],
        loader: () => import('../organization/index'),
    },
    ideas: {
        title: 'Ideas',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'ideas',
        sourceFile: 'index',
        icon: iconLightbulb,
        keywords: 'ideas list innovation',
        cssBundles: ['pages-ideas'],
        loader: () => import('../ideas/index'),
    },
    'idea-detail': {
        title: 'Idea Detail',
        layout: 'sidebar',
        sidebarKey: 'ideas',
        sourceDir: 'ideas',
        sourceFile: 'detail',
        icon: iconLightbulb,
        searchable: false,
        cssBundles: ['pages-ideas'],
        loader: () => import('../ideas/detail'),
    },
    'idea-create': {
        title: 'Create Idea',
        layout: 'sidebar',
        sidebarKey: 'ideas',
        sourceDir: 'ideas',
        sourceFile: 'create',
        icon: iconLightbulb,
        keywords: 'new idea submit',
        cssBundles: ['pages-ideas'],
        loader: () => import('../ideas/create'),
    },
    'idea-convert': {
        title: 'Convert Idea',
        layout: 'sidebar',
        sidebarKey: 'ideas',
        sourceDir: 'ideas',
        sourceFile: 'convert',
        icon: iconLightbulb,
        searchable: false,
        cssBundles: ['pages-ideas'],
        loader: () => import('../ideas/convert'),
    },
    projects: {
        title: 'Projects',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'projects',
        sourceFile: 'index',
        icon: iconFolderKanban,
        keywords:
            'projects list kanban',
        cssBundles: ['pages-projects'],
        loader: () => import('../projects/index'),
    },
    'project-detail': {
        title: 'Project Detail',
        layout: 'sidebar',
        sidebarKey: 'projects',
        sourceDir: 'projects',
        sourceFile: 'detail',
        icon: iconFolderKanban,
        searchable: false,
        cssBundles: ['pages-projects'],
        loader: () => import('../projects/detail'),
    },
    records: {
        title: 'Records',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'records',
        sourceFile: 'index',
        icon: iconDatabase,
        keywords:
            'records data shape attribute',
        cssBundles: ['pages-records'],
        loader: () => import('../records/index'),
    },
    'record-create': {
        title: 'Create Record',
        layout: 'sidebar',
        sidebarKey: 'records',
        sourceDir: 'records',
        sourceFile: 'create',
        icon: iconDatabase,
        keywords: 'new record create',
        cssBundles: ['pages-records'],
        loader: () => import('../records/create'),
    },
    'record-detail': {
        title: 'Record',
        layout: 'sidebar',
        sidebarKey: 'records',
        sourceDir: 'records',
        sourceFile: 'detail',
        icon: iconDatabase,
        searchable: false,
        cssBundles: ['pages-records'],
        loader: () => import('../records/detail'),
    },
    flows: {
        title: 'Flows',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'flows',
        sourceFile: 'index',
        icon: iconGitBranch,
        keywords:
            'flow, process,'
            + ' state machine',
        loader: () => import('../flows/index'),
    },
    'flow-detail': {
        title: 'Flow Designer',
        layout: 'sidebar',
        sidebarKey: 'flows',
        sourceDir: 'flows',
        sourceFile: 'detail',
        icon: iconGitBranch,
        searchable: false,
        cssBundles: ['pages-flow-detail'],
        loader: () => import('../flows/detail'),
    },
    'flow-stats': {
        title: 'Flow Statistics',
        layout: 'sidebar',
        sidebarKey: 'flows',
        sourceDir: 'flows',
        sourceFile: 'stats',
        icon: iconBarChart,
        searchable: false,
        cssBundles: ['pages-flow-stats'],
        loader: () => import('../flows/stats'),
    },
    workbox: {
        title: 'Workbox',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'workbox',
        sourceFile: 'index',
        icon: iconMail,
        keywords:
            'workbox inbox work order',
        cssBundles: ['pages-workbox'],
        loader: () => import('../workbox/index'),
    },
    'workbox-detail': {
        title: 'Work Order',
        layout: 'sidebar',
        sidebarKey: 'workbox',
        sourceDir: 'workbox',
        sourceFile: 'detail',
        icon: iconMail,
        searchable: false,
        cssBundles: ['pages-workbox'],
        loader: () => import('../workbox/detail'),
    },
    members: {
        title: 'Members',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'members',
        sourceFile: 'index',
        icon: iconPeople,
        keywords:
            'members humans AI manage admin',
        cssBundles: ['pages-members'],
        loader: () => import('../members/index'),
    },
    'member-detail': {
        title: 'Member',
        layout: 'sidebar',
        sidebarKey: 'members',
        sourceDir: 'members',
        sourceFile: 'detail',
        icon: iconPerson,
        searchable: false,
        cssBundles: ['pages-members'],
        loader: () => import('../members/detail'),
    },
    identities: {
        title: 'Identities',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'identities',
        sourceFile: 'index',
        icon: iconShield,
        keywords:
            'identities person service'
            + ' credentials providers tokens',
        cssBundles: ['pages-identities'],
        loader: () => import('../identities/index'),
    },
    'identity-detail': {
        title: 'Identity',
        layout: 'sidebar',
        sidebarKey: 'identities',
        sourceDir: 'identities',
        sourceFile: 'detail',
        icon: iconShield,
        searchable: false,
        cssBundles: ['pages-identities'],
        loader: () => import('../identities/detail'),
    },
    'identity-providers': {
        title: 'Identity Providers',
        layout: 'sidebar',
        sidebarKey: 'identities',
        sourceDir: 'identity-providers',
        sourceFile: 'index',
        icon: iconShield,
        searchable: false,
        cssBundles: ['pages-identities'],
        loader: () =>
            import('../identity-providers/index'),
    },
    'identity-tokens': {
        title: 'Tokens',
        layout: 'sidebar',
        sidebarKey: 'identities',
        sourceDir: 'identity-tokens',
        sourceFile: 'index',
        icon: iconShield,
        searchable: false,
        cssBundles: ['pages-identities'],
        loader: () =>
            import('../identity-tokens/index'),
    },
    billing: {
        title: 'Billing',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'billing',
        sourceFile: 'index',
        icon: iconCreditCard,
        keywords:
            'billing plan invoices'
            + ' payment',
        loader: () => import('../billing/index'),
    },
    snapshots: {
        title: 'Snapshots',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'snapshots',
        sourceFile: 'index',
        icon: iconDatabase,
        keywords:
            'data export import wipe',
        requiresSchema: false,
        cssBundles: ['pages-snapshots'],
        loader: () => import('../snapshots/index'),
    },
    'design-system': {
        title: 'Design System',
        layout: 'sidebar',
        inSidebarNav: true,
        sourceDir: 'design-system',
        sourceFile: 'index',
        icon: iconPalette,
        keywords:
            'components ui reference',
        requiresSchema: false,
        cssBundles: ['pages-design-system'],
        loader: () => import('../design-system/index'),
    },
    auth: {
        title: 'Authentication',
        layout: 'standalone',
        sourceDir: 'auth',
        sourceFile: 'index',
        searchable: false,
        requiresSchema: false,
        cssBundles: ['pages-auth'],
        loader: () => import('../auth/index'),
    },
    landing: {
        title: 'Landing',
        layout: 'standalone',
        sourceDir: 'landing',
        sourceFile: 'index',
        searchable: false,
        requiresSchema: false,
        cssBundles: ['pages-landing'],
        loader: () => import('../landing/index'),
    },
    'not-found': {
        title: '404 Not Found',
        layout: 'standalone',
        sourceDir: 'not-found',
        sourceFile: 'index',
        searchable: false,
        requiresSchema: false,
        loader: () => import('../not-found/index'),
    },
};
